# Generated by Django 3.2 on 2021-04-27 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_account_list_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
