# Generated by Django 3.2 on 2021-04-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='lists',
            field=models.ManyToManyField(to='posts.List'),
        ),
    ]
