# Generated by Django 3.2 on 2021-04-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210428_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='lists',
            field=models.ManyToManyField(db_index=True, to='posts.List'),
        ),
        migrations.AlterField(
            model_name='post',
            name='social_network',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter')], db_index=True, default='Facebook', max_length=8, verbose_name='Social Network'),
        ),
    ]
