# Generated by Django 3.2 on 2021-04-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_rename_user_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
